const Fuse = require("fuse.js");


const searchingList = [
    "Eliza",
    "Ana Sayfa",
    "Favoriler",
    "Favorileri Düzenle",
    "STATÜLER",
    "Yönetim Kurulu Üyesi",
    "Genel Ayarlar",
    "Departmanlar",
    "SMS Şablonları",
    "Mail SMTP Tanımları",
    "Rapor Tasarımları",
    "Özel Rapor Tanımları",
    "Referans Derecesi Tanımları",
    "Veri Değişim Logları",
    "Restart Firebird Kontrol Panel",
    "SQL Monitor",
    "SQL Defteri",
    "Kullanıcı",
    "Kullanıcı Kayıt",
    "Kullanıcı Listesi",
    "Gün Sonu İşlemleri",
    "Gün Sonu Analizi",
    "Gün Sonu Raporu",
    "Analiz İşlemleri",
    "Wolvox WebConnect",
    "E-Fatura/E-Arşiv Analizi",
    "Özel Raporlu Satış/İade Analizi",
    "Paket Satış Analizi",
    "Online Ödeme",
    "Online Ödeme Kart Tanımları",
    "Online Ödeme Pos Tanımları",
    "Üst Düzey Yönetici",
    "Mail/SMS Kuyruğu",
    "Açıklama Tanımları",
    "Müşteri Grupları",
    "Otomatik SMS Tanımları",
    "Ülke Tanımları",
    "Şehir Tanımları",
    "Şehir Arama",
    "Çağrı Görev Kayıt",
    "Çağrı Görev Arama",
    "Referans Sektörleri",
    "Referans Sektör Analizi",
    "Site İstatistikleri",
    "Yönetici",
    "Kullanıcı",
    "Kullanıcı Yetkileri",
    "Kullanıcı Giriş Logları",
    "Zamanlı Görev",
    "Zamanlı Görev Kaydı",
    "Zamanlı Görev Arama",
    "E-Ofis",
    "Mesaj Logları",
    "Anlık Ekran İzleme",
    "Kayıtlı Ekran Logları",
    "Gezi Takip",
    "Gezi Takip Kayıt",
    "Gezi Takip Arama",
    "Yazışma/Evrak Takip",
    "Yazışma/Evrak Takip",
    "Yazışma/Evrak Arama",
    "Form Takip",
    "Form Kayıt",
    "Form Arama",
    "İstek-Öneri Cevap",
    "İstek-Öneri Cevap Ara",
    "İstek-Öneri Cevap Kayıt",
    "Personel",
    "Geri Bildirim Gönder",
    "İnsan Kaynakları",
    "Çağrı Görev Arama",
    "İstek-Öneri",
    "İstek Öneri Kayıt",
    "İstek Öneri Arama",
    "DEPARTMAN İŞLEMLERİ",
    "Üretim",
    "Ar-Ge",
    "Ar-Ge Kayıt",
    "Ar-Ge Arama",
    "Ar-Ge Durumları",
    "Ar-Ge Analiz",
    "Ar-Ge Bayi Analiz",
    "Ar-Ge Özel Rapor",
    "Ar-Ge Kayıt Değerlendirme",
    "Programlama",
    "Program",
    "Program Kayıt",
    "Program Arama",
    "Program Web Arama",
    "Program Download",
    "Program Faaliyet Raporu",
    "Program Grupları",
    "Program Beta Kayıtları",
    "Program Beta Raporu",
    "Hata Analizi",
    "Hata Perf.Değerlendirme",
    "Bulut Yazılımlar",
    "E-Ticaret",
    "E-Ticaret Durum Raporu",
    "E-Ticaret Analizi",
    "İnternet Teknolojileri",
    "Link",
    "Link Arama",
    "Link Kayıtları",
    "Domain/Host",
    "Domain/Host Arama",
    "Domain/Host Kayıt",
    "Domain/Host Açıklama Arama",
    "Domain/Host Grupları",
    "Host Mail/SMS Şablonları (Prog)",
    "ISS",
    "ISS Arama",
    "ISS Kayıt",
    "Bayi Ana Sayfa Tasarım",
    "Müşteri Slider Tasarım",
    "Pazarlama",
    "Kurumsal İletişim",
    "Faaliyet Kayıt",
    "Faaliyet Arama",
    "Faaliyet Grupları",
    "Mail Şablonları",
    "Organizasyon",
    "Organizasyon Kayıt",
    "Organizasyon Ara",
    "Rezervasyon",
    "Rezervasyon Arama",
    "Organizasyon Rezv.Kayıt",
    "Reklam-Haber",
    "Reklam-Haber Kayıtları (-)",
    "Reklam-Haber Arama (-)",
    "Güncel Haberler (-)",
    "Robotik",
    "Robotik Fiyat Hesaplama",
    "Robot Teklif Arama",
    "Robotik Ürün Teklif Arama",
    "Müşteri Hizmetleri",
    "Hızlı Demo Oluştur",
    "CRM",
    "Hızlı Ticket",
    "Bayi Sorgula",
    "Teknik Destek",
    "Teknik Destek Kayıt",
    "Teknik Destek Arama",
    "Bayi",
    "Bayi Kayıt",
    "Bayi Arama",
    "Bayi Açıklama Arama",
    "Bayi Rezzta Sözleşme Arama",
    "Bayi Dosya Arama",
    "Bayi Analizi",
    "Bayi Öner",
    "Bayi Haber Kayıt",
    "Bayi Haber Arama",
    "Bayi Özel Haberleri",
    "Bayilik Durumları",
    "Bayi WEB Arama",
    "Bayi Kontenjan Durumu",
    "Bayi Teklif Arama",
    "Bölgesel Personel Kayıt",
    "Kampanya Tanımları",
    "Bayi Ciro Kontrol",
    "Bayi Cari Kontrol",
    "Bayi Paket Rapor",
    "Bölge Bayi Demo Talep Kontrol",
    "Müzayede",
    "Müzayede Arama",
    "Müzayede Kayıt",
    "Performans",
    "Bölgesel Performans",
    "Bölgesel Prim Sistemi",
    "Bayi Bonus",
    "Ana Bayi Bonus",
    "Bölge Bayi Bonus",
    "Bonus Hesaplama Kuyruğu",
    "Bayi Bonus Ayrıntısı",
    "Extra Bonus",
    "Bonus Derece Listesi",
    "Bulmaca",
    "Geçmiş Dönem Bonus",
    "Geçmiş Dönem Bayi Bonus",
    "Geçmiş Dönem Ana Bayi Bonusları",
    "Geçmiş Dönem Bölge Bonusları",
    "Geçmiş Dönem Extra Bonuslar",
    "Geçmiş Dönem Bölgesel Performans",
    "İhale",
    "İhale Kayıtları",
    "İhale Arama",
    "Eğitim",
    "Seminer",
    "Seminer Kayıt",
    "Seminer Arama",
    "Seminer Kişi Kayıt",
    "Seminer Raporu",
    "Sertifika",
    "Sertifika Kayıt",
    "Sertifika Arama",
    "Sertifika Raporu",
    "Sınav",
    "Sınav Anket Kayıt",
    "Sınav Anket Sonuçları",
    "Bayi Sınav Sonuçları",
    "Demo Yönlendirme",
    "Demo Yönlendirme Kayıt",
    "Demo Yönlendirme Arama",
    "Demo Açıklama Arama",
    "İstatistikler",
    "Genel İstatistik",
    "Yurtdışı İstatistik",
    "Dış Ticaret",
    "Çeviriler",
    "Departman Çeviri",
    "Faaliyet Grupları Çeviri",
    "Ülke Fiyat Tanımları",
    "Ülke Fiyat Listesi",
    "Ürün ve Proje",
    "Proje",
    "Proje Kayıt",
    "Proje Arama",
    "Proje Açıklama Arama",
    "Muhasebe ve Finans",
    "Lojistik",
    "Faturalandırma",
    "Diğer Gelirler",
    "Diğer Gelirler Arama",
    "Diğer Gelirler Kayıt",
    "Eşantiyon",
    "Eşantiyon İstek Kayıt",
    "Eşantiyon İstek Arama",
    "Eşantiyon İçerik Hareketleri",
    "Stok",
    "Stok Tanım",
    "Stok Arama",
    "Stok Envanteri",
    "Stok Hareket Girişi",
    "Stok Eski Hareketleri",
    "Stok Grup Girişleri",
    "Kargo",
    "Kargo İçerik Hareketleri",
    "Giden Kargo Kayıt",
    "Gelen Kargo Kayıt",
    "Bugünün Kargoları",
    "Giden Kargolar",
    "Gelen Kargolar",
    "Kargo Arama",
    "Kargo İçerik Kaydı",
    "Kargo İçerik Analizi",
    "Paket",
    "Paket Tanım Kayıt",
    "Paket Tanım Raporu",
    "Paket Toplu Satış Tanım",
    "Paket Satış Raporu",
    "Paket Hareket Raporu",
    "Lisans",
    "Lisans Kayıt",
    "Lisans Arama",
    "Bugünün Lisansları",
    "Bugün Değişen Lisanslar",
    "Süreli Lisans Geçici Şifre",
    "Sipariş Sözleşmeleri",
    "Müşteri",
    "Müşteri Arama",
    "Müşteri Açıklama Arama",
    "Müşteri WEB Arama",
    "Müşteri Ücretsiz Deneme",
    "Ücretsiz Deneme Kayıt",
    "Ücretsiz Deneme Kayıt Ara",
    "İnsan Kaynakları",
    "Hukuk",
    "Hukuk Takip Kayıt",
    "Hukuk Arama",
    "Hukuk Crack Takip Arama",
    "Hukuk Program İade Arama",
    "Hukuk İcra Takip Arama",
    "Hukuk Genel Dava Arama",
    "Hukuk Genel Arama",
    "Hukuk Açıklama Arama",
    "Lisans Kontrol",
    "Extra",
    "Bağlantılar",
    "Web Mail",
    "Bilgi Bankası",
    "SiteCloud Yönetim",
    "Canlı Destek",
    "Daprox Paylaşım",
    "Daprox Paylaşım Yönetim",
    "Çeviri Paneli",
    "Rezzta Yönetim",
    "Extra",
    "Çağrı Görev Kayıt",
    "Çağrı Görev Arama",
    "SQL Monitor",
    "Veri Değişim Logları",
    "Analiz İşlemleri",
    "E-Fatura/E-Arşiv Analizi",
    "Özel Raporlu Satış/İade Analizi",
    "Paket Satış Analizi",
    "Gün Sonu İşlemleri",
    "Gün Sonu Analizi",
    "Gün Sonu Raporu",
    "Form Takip",
    "Form Kayıt",
    "Form Arama",
    "Özel Raporlar",
    "Arge Departmanı Müşteri Ek Gelirleri",
    "Bayi Arge Dağılım",
    "CRM Destek Analizi",
    "ÇO Alış Fiyatlarına Göre Kalan Paketler",
    "Müşteri Bazında Tutar Analizi",
    "Müşteri Form Kullanım Analizi",
    "Müşteri Log Analizi",
    "Program Satış Dağılımı",
    "Wolvox Kullanıcı Analizi",
    "Wolvox Kullanıcı Analizi 2",
    "Wolvox Segment Dağılım Analizi",
    "Wolvox8 Paket Analizi",
    "Yıllara Göre Bölgesel Analiz",
    "Yıllara Göre Paket SKT Analizi",
    "Kalkacak",
    "Kalkacak",
    "Web Kullanıcı Yetkileri",
    "Kullanıcı Rapor Kısıtlama",
    "Ürün Müdürleri",
    "Mail List Arama",
    "Toplu Lisans Kartı Basımı",
    "SSS",
    "SSS Kayıt",
    "SSS Arama",
    "İş Takip",
    "İş Takibi Arama",
    "İş Takibi Kayıt"
];

const searchText = process.argv[2];


var options = {}
var fuse = new Fuse(searchingList, options);
console.log(fuse.search(searchText).map(item => searchingList[item]));

